**Given these home prices find out price of a home that has,**

**3000 sqr ft area, 3 bedrooms, 40 year old**
  
**2500 sqr ft area, 4 bedrooms, 5 year old**

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df = pd.read_csv("../input/homeprices-multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
#preprocessing of dataset
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms', 'age']], df.price)

LinearRegression()

In [5]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [6]:
reg.intercept_

221323.00186540396

In [7]:
#3000 sqr ft area, 3 bedrooms, 40 year old
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [8]:
#Above proof

(112.06244194*3000) + (23388.88007794*3) + (-3231.71790863*40) + 221323.00186540396

498408.251574024

In [9]:
# 2500 sqr ft area, 4 bedrooms, 5 year old
reg.predict([[2500,4,5]])

array([578876.03748933])